version: '3.8'

services:
  frontend:
    image: notatherapist-frontend
    container_name: notatherapist-frontend
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - notatherapist-network
    depends_on:
      - llm_gateway

  llm_gateway:
    build: ./backend/llm_gateway
    image: notatherapist-llm-gateway
    container_name: notatherapist-llm-gateway
    ports:
      - "5004:5004"
    restart: unless-stopped
    environment:
      - BASETEN_API_KEY=jPodC7PX.km2yvG9icviCMGklMgyrbSyxcVdnr3iY
    networks:
      - notatherapist-network

  # Placeholder services - uncomment and configure as needed:
  # input_gateway:
  #   build: ./backend/input_gateway
  #   container_name: notatherapist-input-gateway
  #   ports:
  #     - "5001:5001"
  #   networks:
  #     - notatherapist-network

  # input_processor:
  #   build: ./backend/input_processor
  #   container_name: notatherapist-input-processor
  #   ports:
  #     - "5002:5002"
  #   networks:
  #     - notatherapist-network

  # response_processor:
  #   build: ./backend/response_processor
  #   container_name: notatherapist-response-processor
  #   ports:
  #     - "5005:5005"
  #   networks:
  #     - notatherapist-network

  # response_gateway:
  #   build: ./backend/response_gateway
  #   container_name: notatherapist-response-gateway
  #   ports:
  #     - "5006:5006"
  #   networks:
  #     - notatherapist-network

networks:
  notatherapist-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: