services:
  frontend:
    image: notatherapist-frontend
    container_name: notatherapist-frontend
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - notatherapist-network
    depends_on:
      - backend

  backend:
    image: notatherapist-backend
    container_name: notatherapist-backend
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - notatherapist-network


networks:
  notatherapist-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: