services:
  frontend:
    image: notatherapist-frontend
    container_name: notatherapist-frontend
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - notatherapist-network
    depends_on:
      - backend

  backend:
    build: ./backend/llm_gateway
    image: notatherapist-backend
    container_name: notatherapist-backend
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - notatherapist-network
    depends_on:
      - postgres
    volumes:
      - postgres_socket:/var/run/postgresql
    ports:
      - "5004:5004"

  postgres:
    image: postgres:15-alpine
    container_name: notatherapist-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: notatherapist
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secure_password_here}
      POSTGRES_DB: notatherapist_db
    # SECURITY: Port NOT exposed - use SSH tunnel for external access
    # ports:
    #   - "5432:5432"  # ONLY uncomment for local development
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_socket:/var/run/postgresql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - notatherapist-network
    command: >
      postgres
      -c unix_socket_directories=/var/run/postgresql
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.track=all

networks:
  notatherapist-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  postgres_data:
  postgres_socket: