version: '3.8'

services:
  frontend:
    image: notatherapist-frontend
    container_name: notatherapist
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: